---
- hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    apache_owner: apache
    apache_group: apache
    deploy_dir: /var/www/html
    server_name: rossedman.me
    composer_install_dir: /usr/local/bin/composer
    php_timezone: America/Chicago
    php_ini: /etc/php.ini
    aws_logs:
      - /var/log/messages
      - /var/log/httpd/error_log
      - /var/log/httpd/access_log
      - /var/www/html/storage/logs/laravel.log

  handlers:
    - name: start apache
      service: name=httpd state=started enabled=true

    - name: restart apache
      service: name=httpd state=restarted enabled=true

    - name: restart cloudwatch agent
      service: name=awslogs state=restarted enabled=true

  tasks:
      #------------------------------------
      # php/apache config
      #------------------------------------
    - name: install php
      yum: name={{ item }}
      with_items:
        - httpd24
        - php56
        - php56-common
        - php56-devel
        - php56-cli
        - php56-mbstring
        - php56-mcrypt
        - php56-pdo
        - php56-mysqlnd
        - php56-pecl-memcached

    - name: configure php
      lineinfile: dest={{php_ini}} regexp="^date.timezone" line="date.timezone = {{php_timezone}}"

    - name: add ec2-user to apache group
      user: name=ec2-user groups={{apache_group}} append=yes

    - name: set permissions for deployment
      file: path={{deploy_dir}} owner=ec2-user group={{apache_group}} mode=0755 recurse=yes

      #------------------------------------
      # nodejs install
      #------------------------------------

    # - stat: path=/usr/bin/node
    #   register: node
    #
    # - block:
    #     - name: install node
    #       shell: curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
    #
    #     - name: install nodejs
    #       yum: name=nodejs
    #
    #   when: not node.stat.exists
    #
    # - name: install npm packages
    #   npm: path={{deploy_dir}}

      #------------------------------------
      # composer install
      #------------------------------------
    - stat: path={{composer_install_dir}}
      register: com

    - block:
        - name: download composer installer
          get_url:
            url: https://getcomposer.org/installer
            dest: /tmp/composer-installer.php
            mode: 0755

        - name: run composer installer
          command: >
            php composer-installer.php
            chdir=/tmp

        - name: make composer global
          shell: >
            mv /tmp/composer.phar {{composer_install_dir}}
            creates={{composer_install_dir}}

      when: not com.stat.exists

      #------------------------------------
      # cloudwatch agent
      #------------------------------------
    - name: install cloudwatch logs agent
      yum: name=awslogs

    - name: configure cloudwatch logs
      template: src=/tmp/config/templates/awslogs.conf dest=/etc/awslogs/awslogs.conf
      notify: restart cloduwatch agent

      #------------------------------------
      # laravel configuration
      #------------------------------------
    - stat: path={{deploy_dir}}/storage/logs/laravel.log
      register: larlog

    - name: ensure laravel log exists
      file: path={{deploy_dir}}/storage/logs/laravel.log state=touch mode=0777
      when: not larlog.stat.exists

    - name: copy env file
      copy: src={{deploy_dir}}/.env.deploy dest={{deploy_dir}}/.env remote_src=true owner=apache group=apache

    - name: copy apache conf file
      template: src=templates/laravel.conf dest=/etc/httpd/conf.d/vhosts.conf
      notify: restart apache

    - name: install composer packages
      composer: command=install working_dir={{deploy_dir}}
      become_user: ec2-user

  post_tasks:
    - name: set file perms to 0644
      file: path={{deploy_dir}} mode=0644 recurse=yes owner=apache group=apache

    - name: set directories perms to 0755
      file: path={{deploy_dir}} mode="u=rwX,g=rX,o=rX" recurse=yes owner=apache group=apache

    - name: set bootstrap perms to 0755
      file: path={{deploy_dir}}/bootstrap/cache mode=0775 recurse=yes

    - name: set storage perms to 0777
      file: path={{deploy_dir}}/storage owner=apache group=apache mode=0777 recurse=yes
